### ISSUE TITLE
Build on MacOS

### ISSUE THREAD

**Issue by dawit1989** [bradhowes/sidecar#1]
When i try to build using cmake 3.10 it returns this error on macOS 10.12.
-------------------------------------------------------------
The C compiler identification is AppleClang 9.0.0.9000039
The CXX compiler identification is AppleClang 9.0.0.9000039
Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Version 1.0.0
building RELEASE targets
Installation location: /Users/user/Desktop/sidecar/builds/20180323
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find ACE (missing: ACE_INCLUDE_DIR ACE_LIBRARY)
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  CMakeStuff/FindACE.cmake:10 (find_package_handle_standard_args)
  CMakeStuff/Configuration.cmake:52 (find_package)
  CMakeLists.txt:32 (include)

Configuring incomplete, errors occurred!
See also "/Users/user/Desktop/sidecar-master/build/CMakeFiles/CMakeOutput.log".

**Comment by bradhowes** [comment]
Hi. I have updated the build instructions with additional details pertaining to macOS. From the above, CMake is not able to find an installation for ACE.

**Comment by dawit1989** [comment]
The others work right but I got this new errorCMake Error at CMakeStuff/GUI.cmake:51 (add_executable):
  Cannot find source file:

    ascope.icns

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
Call Stack (most recent call first):
  GUI/AScope/CMakeLists.txt:6 (add_gui)


CMake Error at CMakeStuff/GUI.cmake:51 (add_executable):
  Cannot find source file:

    bscope.icns

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
Call Stack (most recent call first):
  GUI/BScope/CMakeLists.txt:6 (add_gui)


CMake Error at CMakeStuff/GUI.cmake:51 (add_executable):
  Cannot find source file:

    master.icns

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
Call Stack (most recent call first):
  GUI/Master/CMakeLists.txt:6 (add_gui)


CMake Error at CMakeStuff/GUI.cmake:51 (add_executable):
  Cannot find source file:

    ppidisplay.icns

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
Call Stack (most recent call first):
  GUI/PPIDisplay/CMakeLists.txt:5 (add_gui)


CMake Error at CMakeStuff/GUI.cmake:51 (add_executable):
  Cannot find source file:

    priemitter.icns

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
Call Stack (most recent call first):
  GUI/PRIEmitter/CMakeLists.txt:6 (add_gui)


CMake Error at CMakeStuff/GUI.cmake:51 (add_executable):
  Cannot find source file:

    spectrum.icns

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
Call Stack (most recent call first):
  GUI/Spectrum/CMakeLists.txt:8 (add_gui)


CMake Error at CMakeStuff/GUI.cmake:51 (add_executable):
  Cannot find source file:

    zcm.icns

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
Call Stack (most recent call first):
  GUI/ZeroconfMonitor/CMakeLists.txt:6 (add_gui)


CMake Error at CMakeStuff/GUI.cmake:51 (add_executable):
  No SOURCES given to target: ascope
Call Stack (most recent call first):
  GUI/AScope/CMakeLists.txt:6 (add_gui)


CMake Error at CMakeStuff/GUI.cmake:51 (add_executable):
  No SOURCES given to target: bscope
Call Stack (most recent call first):
  GUI/BScope/CMakeLists.txt:6 (add_gui)


CMake Error at CMakeStuff/GUI.cmake:51 (add_executable):
  No SOURCES given to target: master
Call Stack (most recent call first):
  GUI/Master/CMakeLists.txt:6 (add_gui)


CMake Error at CMakeStuff/GUI.cmake:51 (add_executable):
  No SOURCES given to target: ppidisplay
Call Stack (most recent call first):
  GUI/PPIDisplay/CMakeLists.txt:5 (add_gui)


CMake Error at CMakeStuff/GUI.cmake:51 (add_executable):
  No SOURCES given to target: priemitter
Call Stack (most recent call first):
  GUI/PRIEmitter/CMakeLists.txt:6 (add_gui)


CMake Error at CMakeStuff/GUI.cmake:51 (add_executable):
  No SOURCES given to target: spectrum
Call Stack (most recent call first):
  GUI/Spectrum/CMakeLists.txt:8 (add_gui)


CMake Error at CMakeStuff/GUI.cmake:51 (add_executable):
  No SOURCES given to target: zcm
Call Stack (most recent call first):
  GUI/ZeroconfMonitor/CMakeLists.txt:6 (add_gui)

**Comment by bradhowes** [comment]
Thanks for following up. I also got that error, but I thought I had fixed it. Do you have the latest version of the sources (do a `git pull` if you cloned the repo). I added missing `*.icns` files for the GUI apps (they are generated from `*.opacity` files).

**Comment by bradhowes** [comment]
Ah. My bad. I see that I was hiding `*.icns` files in `.gitignore` but I had regenerated them from their source `*.opacity` files. I've checked them into the repo. You should be able to see them now.

**Comment by bradhowes** [comment]
I've update the README doc to be a bit clearer:

Now, try loading the data file `$SIDECAR/data/pri/20t10scans.pri` by selecting "File > Open" (**⌘ O**) and
navigating to the `20t10scans.pri` file. Make sure that the `Connection Type` is set to `Multicast` in the main
window; it defaults to using `TCP`.

**Comment by dawit1989** [comment]
It works well thanks, I like to know what kind of radar data input to PPI display.

**Comment by bradhowes** [comment]
The data formats are found in the `Messages` directory. The class `PRIMessage` defines a base class, and TPRIMessage is a template for different value types. Each PRIMessage is a radar return at a specific azimuth. Each value in the message vector is the reading at a certain time after the radar emits its signal - values near 0 represent reflections close to the radar, while those near the end of the array are reflections furthest from the radar.

I am going to close this ticket now since it works for you.

**Comment by dawit1989** [comment]
Thanks
