### ISSUE TITLE
Fail to build in ubuntu

### ISSUE THREAD

**Issue by amin63moradi** [bradhowes/sidecar#2]
Hi,
in ubuntu 
I have all the prerequisites installed but when installing , I encounter some problems. There are also a lot of stray 'xxx' in program errors. Please let me know how to resolve this issue.

/usr/bin/locale:139:2308: error: stray ‘\1’ in program
/usr/bin/locale:139:2329: error: stray ‘\275’ in program
/usr/bin/locale:139:2352: error: stray ‘\4’ in program
/usr/bin/locale:139:2368: error: stray ‘\1’ in program
/usr/bin/locale:139:2372: error: stray ‘\3’ in program
/usr/bin/locale:139:2392: error: stray ‘\’ in program
/usr/bin/locale:139:2393: error: stray ‘\275’ in program
.
.
.
/usr/bin/locale:4:748: error: expected declaration before ‘}’ token
 pawn_file_actions_destroy memcpy fclose malloc nl_langinfo opendir __xstat64 __ctype_b_loc getenv stderr munmap _obstack_newchunk posix_spawn_file_actions_adddup2 fscanf scandir textdomain twalk strchr obstack_free fprintf alphasort __stpcpy fdopen readdir64 qsort argp_parse __cxa_finalize argz_create_sep posix_spawnp _obstack_begin strcmp __libc_start_main strcoll __overflow __environ GLIBC_2.3 GLIBC_2.15 GLIBC_2.14 GLIBC_2.4 GLIBC_2.2.5 _ITM_deregisterTMCloneTable __gmon_start__ _ITM_registerTMCloneTable                                                                       -     ui    7      P�            P?      X�            ?      h�           �t      x�            ��      ��            �t      ��             �      ��            �t      ��            ��      Ș            u      ؘ            ��      ��            
                  u      ��            ��     �            u      �            ��      H�            $u      X�            ��      h�            -u      x�            ��      ��            5u      ��             �      ��            @u      ��            `�      ș            Mu      ؙ             �      ��            \u      ��             �       �            ��      0�            ��      P�            Ѓ      `�            �t      ��            ��      ��            ��      ��            Ҁ      ��             �      ��            ��      �            H�       �            ��      @�            ��     �           �      (�            �s      H�            �s      h�            �s      ��            �s      ��            �s      Ƞ            nu      ��            �s     �            �s      (�            �s      H�             t      h�             t      ��            t      ��            "t      ȡ            +t      ��            ru     �            {u      (�            �u      H�            �u      h�            �u      ��            �u      ��            �u      Ȣ            �u      ��            �u     �            �u      (�            �u      H�            
                                                                     ^
Logger/CMakeFiles/Logger_objs.dir/build.make:158: recipe for target 'Logger/CMakeFiles/Logger_objs.dir/Formatters.cc.o' failed
make[2]: *** [Logger/CMakeFiles/Logger_objs.dir/Formatters.cc.o] Error 1
CMakeFiles/Makefile2:2487: recipe for target 'Logger/CMakeFiles/Logger_objs.dir/all' failed
make[1]: *** [Logger/CMakeFiles/Logger_objs.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

Thank you.

**Comment by bradhowes** [comment]
Hi. Sorry that you are having difficulties compiling. Unfortunately I have never seen such an error. As far as I know, I do not invoke `locale` anywhere in the build. I suspect that this is an environmental issue. You can perhaps try setting `LC_ALL=en_US.UTF-8` or LC_ALL=C` in your shell and then try compiling. The code was not written with internationalization support.
